- name: Update Api
  hosts: all
  vars:
    date: '{{ lookup(''pipe'', ''date +"%Y%m%d"'') }}'
  tasks:
    - name: update service
      block:
        - name: check node connection
          win_ping:

        - name: Sync content in recursive mode, removing any files/directories found in destination that do not exist in the source
          win_robocopy:
            src: C:\App\XB5_Api01
            dest: C:\AppBackup\webapp{{date}}
            flags: /E /PURGE /XD bettings logs
        - name: stop website & application pool
          win_shell: |
            C:\Windows\System32\inetsrv\appcmd stop apppool /apppool.name: XB5_Api01
            C:\Windows\System32\inetsrv\appcmd stop sites XB5_Api01

        # - name: git pull

        - name: overwrite folder
          win_robocopy:
            src: C:\Git\publish_xb3_xb5_n6\(4)webApp-v1.3.72hotfix2\LotteryWeb
            dest: C:\App\XB5_Api01\
            flags: /E /PURGE /XF Web.config
        - name: start website & application pool
          win_shell: |
            C:\Windows\System32\inetsrv\appcmd start apppool /apppool.name: XB5_Api01
            C:\Windows\System32\inetsrv\appcmd start sites XB5_Api01
        - name: send message
          import_tasks: telegram.yml
          vars:
            msg: "all tasks finished"
      rescue:
        - debug:
            msg: "revert from backup"
        - win_robocopy:
            dest: C:\App\XB5_Api01
            src: C:\AppBackup\webapp{{date}}
        - win_shell: |
            C:\Windows\System32\inetsrv\appcmd start apppool /apppool.name: XB5_Api01
            C:\Windows\System32\inetsrv\appcmd start sites XB5_Api01
        - import_tasks: telegram.yml
          vars:
            msg: "error"
            # msg: "'name': {{ ansible_failed_task.name }}, 'msg': {{ ansible_failed_result.stderr }}"
