---
site: 'XB5_Api01'
git_repository_url: 'http://{{gitlab_user}}:{{gitlab_pwd}}@gitlab.noyasoft.com/operationGroup/publish_xb3_xb5_n6.git'
git_folder_path: 'C:\Git\publish_xb3_xb5_n6'
web_folder: C:\App\{{ site }}
backup_folder: C:\AppBackup\Api\webapp{{ date }}
backup_exclude_folder: 'bettings logs'
backup_exclude_file: ''
update_folder: C:\Git\publish_xb3_xb5_n6\(4)webApp-v1.3.72hotfix2\LotteryWeb
update_exclude_folder: 'Config'
update_exclude_file: 'Web.config'